---@meta

-- Generated platform-native definitions for the RedM product pack.
-- Do not edit this file manually; run npm run update:lua-definitions.

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0xAB7F7241)
---@param conVarFilter string
---@param handler function
---@return integer
function AddConvarChangeListener(conVarFilter, handler) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x5BA35AAF)
---@param keyFilter string
---@param bagFilter string
---@param handler function
---@return integer
function AddStateBagChangeHandler(keyFilter, bagFilter, handler) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0xFA29D35D)
function CancelEvent() end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0xDD76B263)
function ClearDrawOrigin() end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x23EAF899)
---@param url string
---@param width integer
---@param height integer
---@return integer
function CreateDui(url, width, height) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0xFAA3D236)
---@param entity integer
function DeleteEntity(entity) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x1E86F206)
---@param referenceIdentity string
function DeleteFunctionReference(referenceIdentity) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x7389B5DF)
---@param key string
function DeleteResourceKvp(key) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x4152C90)
---@param key string
function DeleteResourceKvpNoSync(key) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0xA085CB10)
---@param duiObject integer
function DestroyDui(duiObject) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x3AC90869)
---@param entity integer
---@return boolean
function DoesEntityExist(entity) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x8B25BC20)
---@param textureId integer
---@return boolean
function DoesTextureExist(textureId) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0xCD4D9DD5)
---@param x1 number
---@param y1 number
---@param z1 number
---@param x2 number
---@param y2 number
---@param z2 number
---@param red integer
---@param green integer
---@param blue integer
---@param alpha integer
function DrawBox(x1, y1, z1, x2, y2, z2, red, green, blue, alpha) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0xB3426BCC)
---@param x1 number
---@param y1 number
---@param z1 number
---@param x2 number
---@param y2 number
---@param z2 number
---@param red integer
---@param green integer
---@param blue integer
---@param alpha integer
function DrawLine(x1, y1, z1, x2, y2, z2, red, green, blue, alpha) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0xABD19253)
---@param x1 number
---@param y1 number
---@param z1 number
---@param x2 number
---@param y2 number
---@param z2 number
---@param x3 number
---@param y3 number
---@param z3 number
---@param red integer
---@param green integer
---@param blue integer
---@param alpha integer
function DrawPoly(x1, y1, z1, x2, y2, z2, x3, y3, z3, red, green, blue, alpha) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0xBA0613E1)
---@param playerSrc string
---@param reason string
function DropPlayer(playerSrc, reason) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0xF4E2079D)
---@param referenceIdentity string
---@return string
function DuplicateFunctionReference(referenceIdentity) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0xB3210203)
---@param handle integer
function EndFindKvp(handle) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x3BB78F05)
---@param entity integer
function EnsureEntityStateBag(entity) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x561C060B)
---@param commandString string
function ExecuteCommand(commandString) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0xBD7BEBC5)
---@param handle integer
---@return string
function FindKvp(handle) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0xD70C3BCA)
---@param traceData any
---@return string
function FormatStackTrace(traceData) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x65C16D57)
---@param entity integer
---@param toggle boolean
function FreezeEntityPosition(entity, toggle) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0xCF143FB9)
---@return any
function GetActivePlayers() end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x2CA8F641)
---@return number
function GetAspectRatio() end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0xADA7DB9D)
---@param flagIndex integer
---@return boolean
function GetClientConfigBool(flagIndex) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0xE57429FA)
---@return string
function GetConsoleBuffer() end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x6CCD2564)
---@param varName string
---@param default_ string
---@return string
function GetConvar(varName, default_) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x7E8EBFE5)
---@param varName string
---@param defaultValue boolean
---@return boolean
function GetConvarBool(varName, defaultValue) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x9E666D)
---@param varName string
---@param defaultValue number
---@return number
function GetConvarFloat(varName, defaultValue) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x935C0AB2)
---@param varName string
---@param default_ integer
---@return integer
function GetConvarInt(varName, default_) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0xACA18ECD)
---@return string
function GetCurrentGameName() end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0xE5E9EBBB)
---@return string
function GetCurrentResourceName() end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x337F0116)
---@param width integer
---@param height integer
function GetCurrentScreenResolution(width, height) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0xEA11BFBA)
---@return string
function GetCurrentServerEndpoint() end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x1655D41D)
---@param duiObject integer
---@return string
function GetDuiHandle(duiObject) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0xDFFBA12F)
---@param x number
---@param y number
---@param z number
---@param radius number
---@param entityType integer
---@param sortByDistance boolean
---@param models any
---@return any
function GetEntitiesInRadius(x, y, z, radius, entityType, sortByDistance, models) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x1647F1CB)
---@param entity integer
---@return vector3
function GetEntityCoords(entity) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x4BDF1867)
---@param bagName string
---@return integer
function GetEntityFromStateBagName(bagName) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x972CC383)
---@param entity integer
---@return number
function GetEntityHeading(entity) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x8E3222B7)
---@param entity integer
---@return integer
function GetEntityHealth(entity) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0xDAFCB3EC)
---@param entity integer
---@return integer
function GetEntityModel(entity) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0xED4B0486)
---@param entity integer
---@return integer
function GetEntityRoutingBucket(entity) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0xB1BD08D)
---@param entity integer
---@return integer
function GetEntityType(entity) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0xC14C9B6B)
---@param entity integer
---@return vector3
function GetEntityVelocity(entity) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x3CC98B25)
---@param resource string
---@param key string
---@return number
function GetExternalKvpFloat(resource, key) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x12B8D689)
---@param resource string
---@param key string
---@return integer
function GetExternalKvpInt(resource, key) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x9080363A)
---@param resource string
---@param key string
---@return string
function GetExternalKvpString(resource, key) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x804B9F7B)
---@return integer
function GetGameBuildNumber() end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0xE8EAA18B)
---@return string
function GetGameName() end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x2B9D4F50)
---@param poolName string
---@return any
function GetGamePool(poolName) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0xA4EA0691)
---@return integer
function GetGameTimer() end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x98EFF6F1)
---@param model string
---@return integer
function GetHashKey(model) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x5F70F5A3)
---@return string
function GetHostId() end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x9F1C4383)
---@return integer
function GetInstanceId() end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x4D52FE5B)
---@return string
function GetInvokingResource() end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0xA6FF71C9)
---@return integer
function GetMinimapType() end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0xDD31EC4E)
---@param ped integer
---@return integer
function GetMount(ped) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0xBDBA226F)
---@param x integer
---@param y integer
function GetNuiCursorPosition(x, y) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0xFF7F66AB)
---@param playerSrc string
---@return integer
function GetNumPlayerIdentifiers(playerSrc) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x63D13184)
---@return integer
function GetNumPlayerIndices() end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x619E4A3D)
---@param playerSrc string
---@return integer
function GetNumPlayerTokens(playerSrc) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x776E864)
---@param resourceName string
---@param metadataKey string
---@return integer
function GetNumResourceMetadata(resourceName, metadataKey) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x863F27B)
---@return integer
function GetNumResources() end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x23473EA4)
---@param password string
---@return string
function GetPasswordHash(password) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x9C5E7C9C)
---@param ped integer
---@param boneId integer
---@param forwardVector vector3
---@param rightVector vector3
---@param upVector vector3
---@param position vector3
function GetPedBoneMatrix(ped, boneId, forwardVector, rightVector, upVector, position) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0xA0F3B420)
---@param ped integer
---@return number
function GetPedScale(ped) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0xF402C171)
---@param ped integer
---@return number
function GetPedWetness(ped) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x2545ADE0)
---@param ped integer
---@return number
function GetPedWetnessHeight(ped) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0xFEE404F9)
---@param playerSrc string
---@return string
function GetPlayerEndpoint(playerSrc) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0xC8A9CE08)
---@param index integer
---@return string
function GetPlayerFromIndex(index) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x344EA166)
---@param serverId integer
---@return integer
function GetPlayerFromServerId(serverId) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0xA56135E0)
---@param bagName string
---@return integer
function GetPlayerFromStateBagName(bagName) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0xE52D9680)
---@param playerSrc string
---@return string
function GetPlayerGuid(playerSrc) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x7302DBCF)
---@param playerSrc string
---@param identiferIndex integer
---@return string
function GetPlayerIdentifier(playerSrc, identiferIndex) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0xA61C8FC6)
---@param playerSrc string
---@param identifierType string
---@return string
function GetPlayerIdentifierByType(playerSrc, identifierType) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x406B4B20)
---@param playerSrc string
---@return string
function GetPlayerName(playerSrc) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x6E31E993)
---@param playerSrc string
---@return integer
function GetPlayerPed(playerSrc) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0xFF1290D4)
---@param playerSrc string
---@return integer
function GetPlayerPing(playerSrc) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x52441C34)
---@param playerSrc string
---@return integer
function GetPlayerRoutingBucket(playerSrc) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x4D97BCC7)
---@param player integer
---@return integer
function GetPlayerServerId(player) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x54C06897)
---@param playerSrc string
---@param index integer
---@return string
function GetPlayerToken(playerSrc, index) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0xD4BEF069)
---@return any
function GetRegisteredCommands() end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x387246B7)
---@param findIndex integer
---@return string
function GetResourceByFindIndex(findIndex) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x97628584)
---@param resource string
---@return any
function GetResourceCommands(resource) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x35BDCEEA)
---@param key string
---@return number
function GetResourceKvpFloat(key) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x557B586A)
---@param key string
---@return integer
function GetResourceKvpInt(key) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x5240DA5A)
---@param key string
---@return string
function GetResourceKvpString(key) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x964BAB1D)
---@param resourceName string
---@param metadataKey string
---@param index integer
---@return string
function GetResourceMetadata(resourceName, metadataKey, index) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x61DCF017)
---@param resourceName string
---@return string
function GetResourcePath(resourceName) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x4039B485)
---@param resourceName string
---@return string
function GetResourceState(resourceName) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x4301E10C)
---@param shapeTestHandle integer
---@param hit boolean
---@param endCoords vector3
---@param surfaceNormal vector3
---@param materialHash integer
---@param entityHit integer
---@return integer
function GetShapeTestResultIncludingMaterial(shapeTestHandle, hit, endCoords, surfaceNormal, materialHash, entityHit) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x78D864C7)
---@param bagName string
---@return any
function GetStateBagKeys(bagName) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x637F4C75)
---@param bagName string
---@param key string
---@return any
function GetStateBagValue(bagName, key) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0xA273060E)
---@param vehicle integer
---@return string
function GetVehicleType(vehicle) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x7EBB9929)
---@param object string
---@return boolean
function IsAceAllowed(object) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0xCF24C52E)
---@return boolean
function IsDuplicityVersion() end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x39C9DC92)
---@return boolean
function IsNuiFocusKeepingInput() end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x98545E6D)
---@return boolean
function IsNuiFocused() end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x43103006)
---@param ped integer
---@return boolean
function IsPedOnMount(ped) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0xDEDAE23D)
---@param playerSrc string
---@param object string
---@return boolean
function IsPlayerAceAllowed(playerSrc, object) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x37CF52CE)
---@param principal string
---@param object string
---@return boolean
function IsPrincipalAceAllowed(principal, object) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x76A9EE1F)
---@param resourceName string
---@param fileName string
---@return string
function LoadResourceFile(resourceName, fileName) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0xC79F44BF)
---@param channel integer
function MumbleAddVoiceChannelListen(channel) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x4D386C9E)
---@param targetId integer
---@param channel integer
function MumbleAddVoiceTargetChannel(targetId, channel) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x32C5355A)
---@param targetId integer
---@param player integer
function MumbleAddVoiceTargetPlayer(targetId, player) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x25F2B65F)
---@param targetId integer
---@param serverId integer
function MumbleAddVoiceTargetPlayerByServerId(targetId, serverId) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0xBF847807)
function MumbleClearVoiceChannel() end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x8555DCBA)
---@param targetId integer
function MumbleClearVoiceTarget(targetId) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x5EA72E76)
---@param targetId integer
function MumbleClearVoiceTargetChannels(targetId) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x912E21DA)
---@param targetId integer
function MumbleClearVoiceTargetPlayers(targetId) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x262663C5)
---@param id integer
function MumbleCreateChannel(id) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0xCC8CA25)
---@param channel integer
---@return boolean
function MumbleDoesChannelExist(channel) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x84E02A32)
---@return number
function MumbleGetTalkerProximity() end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x221C09F1)
---@param serverId integer
---@return integer
function MumbleGetVoiceChannelFromServerId(serverId) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0xE820BC10)
---@return boolean
function MumbleIsActive() end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0xB816370A)
---@return boolean
function MumbleIsConnected() end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x1D5D50C2)
---@param playerSrc integer
---@return boolean
function MumbleIsPlayerMuted(playerSrc) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x33EEF97F)
---@param player integer
---@return boolean
function MumbleIsPlayerTalking(player) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x231523B7)
---@param channel integer
function MumbleRemoveVoiceChannelListen(channel) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x268DB867)
---@param targetId integer
---@param channel integer
function MumbleRemoveVoiceTargetChannel(targetId, channel) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x88CD646F)
---@param targetId integer
---@param player integer
function MumbleRemoveVoiceTargetPlayer(targetId, player) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x930BD34B)
---@param targetId integer
---@param serverId integer
function MumbleRemoveVoiceTargetPlayerByServerId(targetId, serverId) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0xD932A3F3)
---@param state boolean
function MumbleSetActive(state) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x1B1052E2)
---@param distance number
function MumbleSetAudioInputDistance(distance) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x6383526B)
---@param intentHash integer
function MumbleSetAudioInputIntent(intentHash) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x74C597D9)
---@param distance number
function MumbleSetAudioOutputDistance(distance) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0xCC6C2EB1)
---@param playerSrc integer
---@param toggle boolean
function MumbleSetPlayerMuted(playerSrc, toggle) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0xE6EB2CD8)
---@param address string
---@param port integer
function MumbleSetServerAddress(address, port) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0xFE3A3054)
---@param serverId integer
---@param submixId integer
function MumbleSetSubmixForServerId(serverId, submixId) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x74E927B0)
---@param value number
function MumbleSetTalkerProximity(value) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x8737EEE8)
---@param channel integer
function MumbleSetVoiceChannel(channel) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x960A4A95)
---@param targetId integer
function MumbleSetVoiceTarget(targetId) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x61C309E3)
---@param player integer
---@param volume number
function MumbleSetVolumeOverride(player, volume) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0xCE8E25B4)
---@param serverId integer
---@param volume number
function MumbleSetVolumeOverrideByServerId(serverId, volume) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x1E2E3177)
---@param netId integer
---@return boolean
function NetworkDoesEntityExistWithNetworkId(netId) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x5B912C3F)
---@param netId integer
---@return integer
function NetworkGetEntityFromNetworkId(netId) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x526FEE31)
---@param entity integer
---@return integer
function NetworkGetEntityOwner(entity) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x1E546224)
---@param entity integer
---@return integer
function NetworkGetFirstEntityOwner(entity) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x9E35DAB6)
---@param entity integer
---@return integer
function NetworkGetNetworkIdFromEntity(entity) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0xFFEEF513)
---@param playerSrc string
---@return vector3
function NetworkGetVoiceProximityOverrideForPlayer(playerSrc) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x8E8CC653)
---@param requestData string
---@param requestDataLength integer
---@return integer
function PerformHttpRequestInternal(requestData, requestDataLength) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x6B171E87)
---@param requestData any
---@return integer
function PerformHttpRequestInternalEx(requestData) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x90892DED)
---@param jsonString string
function PrintStructuredTrace(jsonString) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0xC795A4A9)
---@param scopeName string
function ProfilerEnterScope(scopeName) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0xB39CA35C)
function ProfilerExitScope() end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0xF8B7D7BB)
---@return boolean
function ProfilerIsRecording() end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x5FA79B0F)
---@param commandName string
---@param handler function
---@param restricted boolean
function RegisterCommand(commandName, handler, restricted) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x281B5448)
---@param listener function
function RegisterConsoleListener(listener) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0xC59B980C)
---@param callbackType string
---@param callback function
function RegisterNuiCallback(callbackType, callback) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0xCD03CDA9)
---@param callbackType string
function RegisterNuiCallbackType(callbackType) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x49C1F6DC)
---@param keymapName string
---@param onKeyDown function
---@param onKeyUp function
---@param rawKeyIndex integer
---@param canBeDisabled boolean
function RegisterRawKeymap(keymapName, onKeyDown, onKeyUp, rawKeyIndex, canBeDisabled) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0xA8AE9C2F)
---@param callbackType string
---@param callback function
function RegisterRawNuiCallback(callbackType, callback) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0xD233A168)
---@param eventName string
function RegisterResourceAsEventHandler(eventName) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x9862B266)
---@param resourceName string
---@param fileName string
---@return string
function RegisterResourceAsset(resourceName, fileName) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x6E38C1B9)
---@param keymapName string
---@param newRawKeyIndex integer
function RemapRawKeymap(keymapName, newRawKeyIndex) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0xEAC49841)
---@param cookie integer
function RemoveConvarChangeListener(cookie) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0xD36BE661)
---@param cookie integer
function RemoveStateBagChangeHandler(cookie) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x1582C7F2)
---@param textureId integer
function RemoveTexture(textureId) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0xA09E7E7B)
---@param resourceName string
---@param fileName string
---@param data string
---@param dataLength integer
---@return boolean
function SaveResourceFile(resourceName, fileName, data, dataLength) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x636F097F)
---@param rootPath string
---@param callback function
function ScanResourceRoot(rootPath, callback) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0xB88A73AD)
---@param resourceName string
function ScheduleResourceTick(resourceName) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0xCD380DA9)
---@param duiObject integer
---@param jsonString string
function SendDuiMessage(duiObject, jsonString) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x5D01F191)
---@param duiObject integer
---@param button string
function SendDuiMouseDown(duiObject, button) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0xD9D7A0AA)
---@param duiObject integer
---@param x integer
---@param y integer
function SendDuiMouseMove(duiObject, x, y) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x1D735B93)
---@param duiObject integer
---@param button string
function SendDuiMouseUp(duiObject, button) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x2D62133A)
---@param duiObject integer
---@param deltaY integer
---@param deltaX integer
function SendDuiMouseWheel(duiObject, deltaY, deltaX) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x8BBE6CC0)
---@param jsonString string
---@return boolean
function SendLoadingScreenMessage(jsonString) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x78608ACB)
---@param jsonString string
---@return boolean
function SendNuiMessage(jsonString) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0xC44C2F44)
---@param toggle boolean
function SetBackfaceculling(toggle) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0xD174EF7E)
---@param flagIndex integer
---@param enabled boolean
function SetClientConfigBool(flagIndex, enabled) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x341B16D2)
---@param varName string
---@param value string
function SetConvar(varName, value) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0xF292858C)
---@param varName string
---@param value string
function SetConvarReplicated(varName, value) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x9338D547)
---@param varName string
---@param value string
function SetConvarServerInfo(varName, value) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x8A7A8DAC)
---@param x number
---@param y number
---@return boolean
function SetCursorLocation(x, y) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0xE10198D5)
---@param x number
---@param y number
---@param z number
---@param is2d boolean
function SetDrawOrigin(x, y, z, is2d) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0xF761D9F3)
---@param duiObject integer
---@param url string
function SetDuiUrl(duiObject, url) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0xDF70B41B)
---@param entity integer
---@param xPos number
---@param yPos number
---@param zPos number
---@param alive boolean
---@param deadFlag boolean
---@param ragdollFlag boolean
---@param clearArea boolean
function SetEntityCoords(entity, xPos, yPos, zPos, alive, deadFlag, ragdollFlag, clearArea) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0xD3A183A3)
---@param entity integer
---@param radius number
function SetEntityDistanceCullingRadius(entity, radius) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0xE0FF064D)
---@param entity integer
---@param heading number
function SetEntityHeading(entity, heading) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x489E9162)
---@param entity integer
---@param orphanMode integer
function SetEntityOrphanMode(entity, orphanMode) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x635E5289)
---@param entity integer
---@param bucket integer
function SetEntityRoutingBucket(entity, bucket) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0xFF5A1988)
---@param entity integer
---@param x number
---@param y number
---@param z number
function SetEntityVelocity(entity, x, y, z) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0xF90B7469)
---@param gametypeName string
function SetGameType(gametypeName) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0xF5C6330C)
---@param handler function
function SetHttpHandler(handler) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x85A10FFD)
---@param ignore boolean
function SetIgnoreVehicleOwnershipForStowing(ignore) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0xB7BA82DC)
---@param mapName string
function SetMapName(mapName) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x5FB53015)
---@param type integer
function SetMinimapType(type) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x5B98AE30)
---@param hasFocus boolean
---@param hasCursor boolean
function SetNuiFocus(hasFocus, hasCursor) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x3FF5E5F8)
---@param keepInput boolean
function SetNuiFocusKeepInput(keepInput) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x3734AAFF)
---@param zIndex integer
function SetNuiZindex(zIndex) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x6504EB38)
---@param playerSrc string
---@param bucket integer
function SetPlayerRoutingBucket(playerSrc, bucket) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x21C7A35B)
---@param key string
---@param value string
function SetResourceKvp(key, value) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x9ADD2938)
---@param key string
---@param value number
function SetResourceKvpFloat(key, value) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x3517BFBE)
---@param key string
---@param value number
function SetResourceKvpFloatNoSync(key, value) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x6A2B1E8)
---@param key string
---@param value integer
function SetResourceKvpInt(key, value) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x26AEB707)
---@param key string
---@param value integer
function SetResourceKvpIntNoSync(key, value) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0xCF9A2FF)
---@param key string
---@param value string
function SetResourceKvpNoSync(key, value) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0xA0F2201F)
---@param bucketId integer
---@param mode string
function SetRoutingBucketEntityLockdownMode(bucketId, mode) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0xCE51AC2C)
---@param bucketId integer
---@param mode boolean
function SetRoutingBucketPopulationEnabled(bucketId, mode) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x8D50E33A)
---@param bagName string
---@param keyName string
---@param valueData string
---@param valueLength integer
---@param replicated boolean
function SetStateBagValue(bagName, keyName, valueData, valueLength, replicated) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0xADA9255D)
---@param fontId integer
function SetTextFontForCurrentCommand(fontId) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x68CDFA60)
---@param justifyType integer
function SetTextJustification(justifyType) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x6F60AB54)
---@param start number
---@param endValue number
function SetTextWrap(start, endValue) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0xB9234AFB)
function ShutdownLoadingScreenNui() end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x8F2EECC3)
---@param resourceName string
---@param prefix string
---@return integer
function StartFindExternalKvp(resourceName, prefix) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0xDD379006)
---@param prefix string
---@return integer
function StartFindKvp(prefix) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x29B440DC)
---@param resourceName string
---@return boolean
function StartResource(resourceName) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x12A330)
---@param bagName string
---@param key string
---@return boolean
function StateBagHasKey(bagName, key) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x21783161)
---@param resourceName string
---@return boolean
function StopResource(resourceName) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x1E35DBBA)
---@param playerSrc string
---@param reason string
function TempBanPlayer(playerSrc, reason) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x2F7A49E6)
---@param eventName string
---@param eventTarget string
---@param eventPayload string
---@param payloadLength integer
function TriggerClientEventInternal(eventName, eventTarget, eventPayload, payloadLength) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x91310870)
---@param eventName string
---@param eventPayload string
---@param payloadLength integer
function TriggerEventInternal(eventName, eventPayload, payloadLength) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x70B35890)
---@param eventName string
---@param eventTarget string
---@param eventPayload string
---@param payloadLength integer
---@param bps integer
function TriggerLatentClientEventInternal(eventName, eventTarget, eventPayload, payloadLength, bps) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x128737EA)
---@param eventName string
---@param eventPayload string
---@param payloadLength integer
---@param bps integer
function TriggerLatentServerEventInternal(eventName, eventPayload, payloadLength, bps) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x7FDD1128)
---@param eventName string
---@param eventPayload string
---@param payloadLength integer
function TriggerServerEventInternal(eventName, eventPayload, payloadLength) end

---**RedM platform** `client`
---[Native documentation](https://docs.fivem.net/natives/?_0x7FB46432)
---@param callbackType string
function UnregisterRawNuiCallback(callbackType) end

---**RedM platform** `server`
---[Native documentation](https://docs.fivem.net/natives/?_0x2E310ACD)
---@param password string
---@param hash string
---@return boolean
function VerifyPasswordHash(password, hash) end

---**RedM platform** `shared`
---[Native documentation](https://docs.fivem.net/natives/?_0x58382A19)
---@return boolean
function WasEventCanceled() end

