import fs from "node:fs";
import path from "node:path";

import { REDM_MANIFEST_WARNING } from "./manifestModel";

export const STARTER_RESOURCE_TEMPLATES = ["lua", "static-nui", "react-nui", "vue-nui"] as const;
export type StarterResourceTemplate = typeof STARTER_RESOURCE_TEMPLATES[number];

const MAX_TEMPLATE_FILES = 64;
const MAX_TEMPLATE_DEPTH = 8;
const MAX_TEMPLATE_BYTES = 2 * 1024 * 1024;
const RESOURCE_NAME_PLACEHOLDER = "__QB_RESOURCE_NAME__";

export function requireStarterResourceTemplate(value: unknown): StarterResourceTemplate {
  if (typeof value !== "string" || !STARTER_RESOURCE_TEMPLATES.includes(value as StarterResourceTemplate)) {
    throw new Error("Choose a supported starter-resource template.");
  }
  return value as StarterResourceTemplate;
}

function gameBlock(game: "gta5" | "rdr3"): string {
  return game === "rdr3"
    ? `game 'rdr3'\nrdr3_warning '${REDM_MANIFEST_WARNING}'`
    : `game 'gta5'`;
}

function manifest(game: "gta5" | "rdr3", template: StarterResourceTemplate): string {
  const metadata = `fx_version 'cerulean'\n${gameBlock(game)}\n\n` +
    `description '${template === "lua" ? "Lua" : template === "static-nui" ? "Static NUI" : template === "react-nui" ? "React NUI" : "Vue NUI"} starter resource generated by QB Studio'\n` +
    `version '1.0.0'\n\n` +
    `shared_script 'config.lua'\n` +
    `client_script 'client.lua'\n` +
    `server_script 'server.lua'\n`;
  if (template === "lua") return metadata;
  if (template === "static-nui") {
    return metadata + `\nui_page 'html/index.html'\n\nfiles {\n` +
      `    'html/index.html',\n    'html/style.css',\n    'html/script.js',\n}\n`;
  }
  return metadata + `\nui_page 'html/dist/index.html'\n\nfiles {\n    'html/dist/**/*',\n}\n`;
}

function luaCommonFiles(): Record<string, string> {
  return {
    "config.lua": `-- This file loads on both client and server. Do not put private values here.\n` +
      `Config = {\n    Debug = false,\n}\n`,
    "client.lua": `-- Add client-side behavior here. Keep authoritative state on the server.\n` +
      `if Config.Debug then\n    print(('[%s] client initialized'):format(GetCurrentResourceName()))\nend\n`,
    "server.lua": `-- Add server-side behavior here. Treat client-provided values as untrusted.\n` +
      `if Config.Debug then\n    print(('[%s] server initialized'):format(GetCurrentResourceName()))\nend\n`,
  };
}

function nuiCommonFiles(resourceName: string): Record<string, string> {
  return {
    "config.lua": `-- This file loads on both client and server. Do not put private values here.\n` +
      `Config = {\n    Debug = false,\n    Command = '${resourceName}:ui',\n    Title = '${resourceName} UI',\n}\n`,
    "client.lua": `local visible = false\n\n` +
      `local function setVisible(nextVisible)\n` +
      `    visible = nextVisible == true\n` +
      `    SetNuiFocus(visible, visible)\n` +
      `    SendNUIMessage({\n` +
      `        type = visible and 'qb-studio:open' or 'qb-studio:close',\n` +
      `        title = Config.Title,\n` +
      `    })\n` +
      `end\n\n` +
      `RegisterCommand(Config.Command, function()\n    setVisible(not visible)\nend, false)\n\n` +
      `RegisterNUICallback('close', function(_, cb)\n` +
      `    setVisible(false)\n` +
      `    cb({ ok = true })\n` +
      `end)\n\n` +
      `AddEventHandler('onResourceStop', function(resourceName)\n` +
      `    if resourceName == GetCurrentResourceName() then SetNuiFocus(false, false) end\n` +
      `end)\n`,
    "server.lua": `-- Add authoritative server-side behavior here. Treat client-provided values as untrusted.\n` +
      `if Config.Debug then\n    print(('[%s] server initialized'):format(GetCurrentResourceName()))\nend\n`,
  };
}

function ordinaryTemplateDirectory(rootValue: string, template: StarterResourceTemplate): string {
  const root = path.resolve(rootValue);
  const rootStat = fs.lstatSync(root);
  if (!rootStat.isDirectory() || rootStat.isSymbolicLink()) throw new Error("Starter template catalog is unavailable.");
  const directory = path.resolve(root, template);
  if (path.relative(root, directory).startsWith("..") || path.isAbsolute(path.relative(root, directory))) {
    throw new Error("Starter template catalog path is invalid.");
  }
  const stat = fs.lstatSync(directory);
  if (!stat.isDirectory() || stat.isSymbolicLink()) throw new Error(`Starter template "${template}" is unavailable.`);
  return directory;
}

function readBoundedTemplateFile(absolute: string, relative: string, remainingBytes: number): Buffer {
  const initial = fs.lstatSync(absolute);
  if (!initial.isFile() || initial.isSymbolicLink()) {
    throw new Error(`Starter template file "${relative}" is not an ordinary file.`);
  }
  if (initial.size > remainingBytes) throw new Error("Starter template exceeds the supported size.");

  const descriptor = fs.openSync(absolute, "r");
  const chunks: Buffer[] = [];
  let total = 0;
  try {
    const opened = fs.fstatSync(descriptor);
    if (!opened.isFile() || opened.size > remainingBytes) {
      throw new Error("Starter template exceeds the supported size.");
    }
    while (true) {
      const capacity = Math.min(64 * 1024, remainingBytes - total + 1);
      const buffer = Buffer.allocUnsafe(Math.max(1, capacity));
      const count = fs.readSync(descriptor, buffer, 0, buffer.length, null);
      if (count === 0) break;
      total += count;
      if (total > remainingBytes) throw new Error("Starter template exceeds the supported size.");
      chunks.push(buffer.subarray(0, count));
    }
  } finally {
    fs.closeSync(descriptor);
  }
  return Buffer.concat(chunks, total);
}

function loadTemplateAssets(rootValue: string, template: Exclude<StarterResourceTemplate, "lua">, resourceName: string): Record<string, string> {
  const directory = ordinaryTemplateDirectory(rootValue, template);
  const pending: Array<{ directory: string; relative: string; depth: number }> = [{ directory, relative: "", depth: 0 }];
  const files: Record<string, string> = {};
  let count = 0;
  let totalBytes = 0;

  for (let index = 0; index < pending.length; index += 1) {
    const current = pending[index];
    if (current.depth > MAX_TEMPLATE_DEPTH) throw new Error("Starter template exceeds the supported directory depth.");
    for (const entry of fs.readdirSync(current.directory, { withFileTypes: true })) {
      if (entry.isSymbolicLink()) throw new Error("Starter templates cannot contain symbolic links or junctions.");
      if (["node_modules", ".git"].includes(entry.name)) throw new Error(`Starter template contains forbidden directory "${entry.name}".`);
      const relative = current.relative ? `${current.relative}/${entry.name}` : entry.name;
      const absolute = path.join(current.directory, entry.name);
      if (entry.isDirectory()) {
        pending.push({ directory: absolute, relative, depth: current.depth + 1 });
        continue;
      }
      if (!entry.isFile()) throw new Error("Starter templates may contain only ordinary files and directories.");
      if (++count > MAX_TEMPLATE_FILES) throw new Error(`Starter template exceeds ${MAX_TEMPLATE_FILES} files.`);
      const content = readBoundedTemplateFile(absolute, relative, MAX_TEMPLATE_BYTES - totalBytes);
      totalBytes += content.byteLength;
      if (content.includes(0)) throw new Error(`Starter template file "${relative}" is not text.`);
      files[relative] = content.toString("utf8").replaceAll(RESOURCE_NAME_PLACEHOLDER, resourceName);
    }
  }
  return files;
}

function validateNuiAssets(template: Exclude<StarterResourceTemplate, "lua">, files: Record<string, string>): void {
  const required = template === "static-nui"
    ? ["html/index.html", "html/style.css", "html/script.js"]
    : ["README.md", "THIRD_PARTY_NOTICES.txt", "html/package.json", "html/package-lock.json", "html/vite.config.js", "html/index.html", "html/dist/index.html"];
  for (const file of required) {
    if (!(file in files)) throw new Error(`Starter template is missing required file "${file}".`);
  }
  if (Object.values(files).some((content) => content.includes(RESOURCE_NAME_PLACEHOLDER))) {
    throw new Error("Starter template contains an unresolved resource-name placeholder.");
  }
  if (template !== "static-nui" && !Object.keys(files).some((file) => /^html\/dist\/assets\/[^/]+\.js$/.test(file))) {
    throw new Error("Framework starter template is missing its prebuilt JavaScript output.");
  }
}

export function starterResourceFiles(
  templateCatalogRoot: string,
  template: StarterResourceTemplate,
  game: "gta5" | "rdr3",
  resourceName: string,
): Record<string, string> {
  const files: Record<string, string> = {
    "fxmanifest.lua": manifest(game, template),
    ...(template === "lua" ? luaCommonFiles() : nuiCommonFiles(resourceName)),
  };
  if (template !== "lua") {
    const assets = loadTemplateAssets(templateCatalogRoot, template, resourceName);
    validateNuiAssets(template, assets);
    Object.assign(files, assets);
  }
  return files;
}
